version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers: []
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci):"
  - name: 删除运行记录
    uses: Mattraks/delete-workflow-runs@main
    with:
      token: ${{ github.token }}
      delete_workflow_pattern: "dependabot.yaml"
      keep_minimum_runs: 2